bundler_args: "--path vendor/bundle"
before_install:
  - git fetch --depth=1000000
  - gem install cocoapods --user-install
  # - gem install bundler
install:
  - brew install swiftlint
  - bundle update
  - pod update
  - carthage update --platform ios --cache-builds --new-resolver
after_install:

os:
  - osx
osx_image:
  - xcode10.2
language:
  - swift
script:
  - bundle exec fastlane scan --workspace "QuickNews.xcworkspace" --scheme "QuickNews" --clean
  - bundle exec danger
  - swiftlint
